### PR TITLE
Elula Peer Review

### PR DESCRIPTION
**Pull request by tharradine**
Hi guys,

I'm just opening this PR to have one place to give feedback for the client peer review.

Thanks :)

### CODE REVIEW

**Comment by HninPwint** [comment]
Thanks, Toby.

**Comment by tharradine** [comment]
Sorry I didn't mean to have the PR merged, just wanted it open so I could leave inline comments on the code. But it doesn't look like this method was going to work for me, so I'm gonna try something different :D

**Comment by HninPwint** [comment]
Hi Toby,
Please feel free to make a new PR for the next reviews. Thank you.

**Comment by tharradine** [comment]
My full review is now over here: https://github.com/tharradine/addrmatcher/pull/1#pullrequestreview-798464035

**Pull request merged**
